version: '2'

services:
  parity:
    image: parity/parity:v1.7.11
    restart: always
    ports:
      - 8545:8545
      - 8546:8546
      - 8180:8180

  mainnet:
    extends:
      service: parity
    volumes:
      - mainnet:/parity-data/
      - ./keys:/parity-data/keys
    command: >
      --warp
      --pruning fast
      --cache-size 2048
      --base-path /parity-data
      --jsonrpc-interface all
      --jsonrpc-cors *
      --ui-interface all
      --ws-interface all
      --ws-origins all

  kovan:
    extends:
      service: parity
    volumes:
      - kovan:/parity-data/
      - ./keys:/parity-data/keys
    command: >
      --chain kovan
      --warp
      --pruning fast
      --cache-size 2048
      --base-path /parity-data
      --jsonrpc-interface all
      --jsonrpc-cors *
      --ui-interface all
      --ws-interface all
      --ws-origins all

volumes:
  kovan:
  mainnet:
