version: '2'

services:
  parity:
    image: parity/parity:v1.7.11
    restart: always
    volumes:
      - ./keys:/parity-data/keys
      - ./config:/parity-data/config
    ports:
      - 8545:8545
      - 8546:8546
      - 8180:8180

  mainnet:
    extends:
      service: parity
    volumes:
      - mainnet:/parity-data/
    command: >
      --config "/parity-data/config/common.toml"

  kovan:
    extends:
      service: parity
    volumes:
      - kovan:/parity-data/
    command: >
      --chain kovan
      --config "/parity-data/config/common.toml"

volumes:
  kovan:
  mainnet:
