[parity]
base_path = "/parity-data"

[network]
warp = true

[footprint]
pruning = "fast"
cache_size = 2048

[rpc]
interface = "0.0.0.0"
cors = "*"

[websockets]
interface = "0.0.0.0"
origins = ["http://localhost:8180"]

[ui]
force = true
interface = "0.0.0.0"
